version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: gerboyle/reverseproxy
  backend_user:
    build:
      context: ./udagram-api-user
    image: gerboyle/udagram-api-user
  backend_feed:
    build:
      context: ../../udagram-api-feed
    image: gerboyle/udagran-api-feed
  frontend:
    build:
      context: ../../udagram-frontend  
    image: gerboyle/udagram-frontend
