version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: dockerUser/reverseproxy 
  backend_user:
    build:
      context: ../../udagram-api-user
    image: dockerUser/udagram-api-user
  backend_feed:
    build:
      context: ../../udagram-api-feed
    image: dockerUser/udagram-api-feed
  frontend:
    build:
      context: ../../udagram-frontend 
    image: dockerUser/udagram-frontend:local
