version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: gerboyle/reverseproxy 
  backend_user:
    build:
      context: ../../udacity/project
    image: gerboyle/udagram-api-user
  backend_feed:
    build:
      context: ../../udacity/project
    image: gerboyle/udagram-api-feed
  frontend:
    build:
      context: ../../udacity/project 
    image: gerboyle/udagram-frontend:local
