version: "3"
services:
  reverseproxy:
    build:
      context: ./reverseproxy
    image: gerboyle/reverseproxy
  backend_user:
    build:
      context: ./udagram-api-users
    image: gerboyle/udagram-api-users
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: gerboyle/udagram-api-feed
  frontend:
    build:
      context: ./udagram-frontend  
    image: gerboyle/udagram-frontend
